name: SonarQube Analyze Changed Module

on:
  push:
    branches:
      - main # main 브랜치에 push 시 이벤트 트리거

jobs:
  detect-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 커밋 내역을 가져옴.

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Detect changed modules
        id: changes
        run: |
          echo "[DEBUG] Event: ${{ github.event_name }}"
          echo "[DEBUG] Before: ${{ github.event.before }}"
          echo "[DEBUG] After: ${{ github.sha }}"

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$CHANGED_FILES" | grep '^javame-' | cut -d '/' -f1 | sort -u > changed-modules.txt
          
          echo "[DEBUG] Changed files:"
          cat changed-modules.txt
          
          # GitHub Actions에서 multi-line 출력을 위한 방법
          echo "modules<<EOF" >> $GITHUB_OUTPUT
          cat changed-modules.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run SonarQube scans for each changed module
        if: steps.changes.outputs.modules != ''
        run: |
          while IFS= read -r module; do
            echo "[INFO] Running SonarQube scan for changed module: $module"
            mvn -B clean verify sonar:sonar \
              -Dsonar.projectKey=javame-project \
              -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.inclusions=$module/** \
              -Dsonar.coverage.jacoco.xmlReportPaths=$module/target/site/jacoco/jacoco.xml
          done < changed-modules.txt
