name: SonarQube Analyze Changed Module

on:
  push:
    branches:
      - main # main 브랜치에 push 시 이벤트 트리거

jobs:
  detect-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 커밋 내역을 가져옴.

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Detect changed module
        id: changes
        run: |
          echo "[DEBUG] Event: ${{ github.event_name }}"
          echo "[DEBUG] Before: ${{ github.event.before }}"
          echo "[DEBUG] After: ${{ github.sha }}"

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo "[DEBUG] Changed files:"
          echo "$CHANGED_FILES"
          
          # 변경된 파일 중 javame- 로 시작하는 모듈만 추출
          CHANGED_MODULE=$(echo "$CHANGED_FILES" | grep '^javame-' | cut -d '/' -f1 | sort -u | head -n 1)
          
          # 결과 출력
          echo "Changed module: $CHANGED_MODULE"
          echo "module=$CHANGED_MODULE" >> $GITHUB_OUTPUT

      - name: Run SonarQube scan
        if: steps.changes.outputs.module != ''
        run: |
          cd ${{ steps.changes.outputs.module }}
          mvn -X clean verify sonar:sonar \
            -Dsonar.projectKey=${{ steps.changes.outputs.module }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
